import { ApiResponseForCharType, ApiResponseType } from '../../types';

export const responseData: ApiResponseType = {
  data: [
    {
      id: '20448207-20d2-48cb-85b4-d61ee8f50f97',

      attributes: {
        slug: '1992-gryffindor-vs-slytherin-quidditch-match-spectators',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: null,
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'No one knows',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: [],
        marital_status: null,
        name: '1992 Gryffindor vs Slytherin Quidditch match spectators',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: null,
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/1992_Gryffindor_vs_Slytherin_Quidditch_match_spectators',
      },
    },
    {
      id: 'ba22f019-15ad-480c-a5ea-010382cadf55',

      attributes: {
        slug: '1996-gryffindor-quidditch-keeper-trials-spectators',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: null,
        died: null,
        eye_color: null,
        family_members: [],
        gender: null,
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: [],
        marital_status: null,
        name: '1996 Gryffindor Quidditch Keeper trials spectators',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: null,
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/1996_Gryffindor_Quidditch_Keeper_trials_spectators',
      },
    },
    {
      id: '015c91ba-bc7f-4622-a571-0b5e2488fefe',

      attributes: {
        slug: '2-headed-baby',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: 'Before 1927',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Male (most likely)',
        hair_color: null,
        height: null,
        house: null,
        image:
          'https://static.wikia.nocookie.net/harrypotter/images/a/a6/2HeadedBaby.jpg',
        jobs: ['Circus performers'],
        marital_status: null,
        name: '2-Headed Baby',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/2-Headed_Baby',
      },
    },
    {
      id: '4e1a392e-012d-4bd3-8040-2821150d4bac',

      attributes: {
        slug: 'unidentified-8-year-old-muggle-girl',
        alias_names: [],
        animagus: null,
        blood_status: 'Muggle',
        boggart: null,
        born: '1983',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Female',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: [],
        marital_status: null,
        name: '8-year-old Muggle girl',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Unidentified_8-year-old_Muggle_girl',
      },
    },
    {
      id: '6f590753-c40b-42e5-90ca-3aa1c0180792',

      attributes: {
        slug: 'aamir-loonat',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: '31 August 1982 or earlier',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Male',
        hair_color: null,
        height: null,
        house: 'Gryffindor',
        image: null,
        jobs: [],
        marital_status: null,
        name: 'Aamir Loonat',
        nationality: 'British or Irish',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Aamir_Loonat',
      },
    },
    {
      id: '5c2f1c50-2fbe-4344-8fec-b0b018a995e6',

      attributes: {
        slug: 'abbott',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: null,
        died: 'Before 24 December, 1997',
        eye_color: null,
        family_members: [
          'Hannah Abbott (possibly)',
          "Hannah Abbott's mother (possibly)",
          'Giffard Abbott (possibly)',
          'Abbott family',
        ],
        gender: null,
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: [],
        marital_status: null,
        name: 'Abbott',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: null,
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abbott',
      },
    },
    {
      id: '392b2d1c-648b-4f2d-8124-34b3ff75d40a',

      attributes: {
        slug: 'abel-treetops',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: 'Before 1832',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Male',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: ['Con artist'],
        marital_status: null,
        name: 'Abel Treetops',
        nationality: 'American',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abel_Treetops',
      },
    },
    {
      id: '3c305e51-7129-4272-b1d6-90e25a599a2e',

      attributes: {
        slug: 'aberforth-dumbledore',
        alias_names: ['Ab'],
        animagus: null,
        blood_status: 'Half-blood',
        boggart: null,
        born: 'Between 1 September 1883 and 31 August 1884, Mould-on-the-Wold, England, Great Britain (presumably)',
        died: null,
        eye_color: 'Bright blue',
        family_members: [
          'Percival Dumbledore (father) †',
          'Kendra Dumbledore (mother) †',
          'Albus Dumbledore (older brother) †',
          'Ariana Dumbledore (youngest sister) †',
          'Aurelius Dumbledore (biological son)',
          'Honoria (aunt)',
          'Dumbledore family',
        ],
        gender: 'Male',
        hair_color: 'Grey',
        height: null,
        house: null,
        image:
          'https://static.wikia.nocookie.net/harrypotter/images/4/40/Aberforth_Dumbledore.jpg',
        jobs: ["Owner and Barman of the Hog's Head Inn"],
        marital_status: null,
        name: 'Aberforth Dumbledore',
        nationality: 'English',
        patronus: 'Goat',
        romances: ["Aurelius Dumbledore's mother (former lover)"],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: ['Unknown length, wood and core'],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Aberforth_Dumbledore',
      },
    },
    {
      id: '6769c068-14c7-4e5c-923b-bfdb1764fd39',

      attributes: {
        slug: 'abernathy',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: 'Before 1909 (likely)',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Male',
        hair_color: null,
        height: null,
        house: null,
        image:
          'https://static.wikia.nocookie.net/harrypotter/images/a/a6/Abernathy_COG.png',
        jobs: ['Supervisor for the Wand Permit Office (formerly)'],
        marital_status: null,
        name: 'Abernathy',
        nationality: 'American',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: ['Unknown length, wood and core (formerly)'],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abernathy',
      },
    },
    {
      id: 'c68ebdcf-c63d-4c7b-972c-b8af05f5ee48',

      attributes: {
        slug: 'abigail-grey',
        alias_names: [],
        animagus: null,
        blood_status: 'Half-blood',
        boggart: null,
        born: 'Between 1 September 1992 and 31 August 1997',
        died: null,
        eye_color: 'Blue',
        family_members: [
          'Gerard Grey (father)',
          'Diana Grey (mother)',
          'Grey family',
        ],
        gender: 'Female',
        hair_color: 'Red',
        height: null,
        house: 'Gryffindor',
        image:
          'https://static.wikia.nocookie.net/harrypotter/images/a/af/Abigail_Grey_MA.jpeg',
        jobs: [],
        marital_status: null,
        name: 'Abigail Grey',
        nationality: 'British or Irish',
        patronus: 'Wolf',
        romances: [],
        skin_color: 'White',
        species: 'Human (werewolf)',
        titles: [],
        wands: ["11¼', Cypress, unicorn hair"],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abigail_Grey',
      },
    },
    {
      id: '718b0402-89a1-4d8d-9ba1-ac99d5a3a4e8',

      attributes: {
        slug: 'abigail-nicola',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: null,
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Female',
        hair_color: null,
        height: null,
        house: 'Gryffindor',
        image: null,
        jobs: [],
        marital_status: null,
        name: 'Abigail Nicola',
        nationality: 'British or Irish',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abigail_Nicola',
      },
    },
    {
      id: '1adfb759-b212-4650-8f0d-ee4870684600',

      attributes: {
        slug: 'abigail-pugh',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: '31 August 1982 or earlier',
        died: null,
        eye_color: 'Brown',
        family_members: [],
        gender: 'Female',
        hair_color: 'Black',
        height: null,
        house: 'Slytherin',
        image:
          'https://static.wikia.nocookie.net/harrypotter/images/2/2f/Abigail_Pugh.png',
        jobs: [],
        marital_status: null,
        name: 'Abigail Pugh',
        nationality: 'British or Irish',
        patronus: null,
        romances: [],
        skin_color: 'Light',
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abigail_Pugh',
      },
    },
    {
      id: '92819351-45c3-4cb7-879f-f6951897ec34',

      attributes: {
        slug: 'abigail-r-cankus',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: null,
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Female',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: ['Author'],
        marital_status: null,
        name: 'Abigail R. Cankus',
        nationality: 'American',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Abigail_R._Cankus',
      },
    },
    {
      id: 'a7b23980-66d4-4e23-96fc-ee1a0bf03f99',

      attributes: {
        slug: 'able-fleming',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: 'Before 1776, United States of America',
        died: null,
        eye_color: null,
        family_members: [],
        gender: 'Male',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: [
          'President of the Magical Congress of the United States of America (c. 1770s-?)',
        ],
        marital_status: null,
        name: 'Able Fleming',
        nationality: 'American',
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: ['President'],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Able_Fleming',
      },
    },
    {
      id: '944f790b-f435-4f88-a9d2-895df3b79dd2',

      attributes: {
        slug: 'able-spudmore',
        alias_names: [],
        animagus: null,
        blood_status: null,
        boggart: null,
        born: 'In or before 1923',
        died: null,
        eye_color: null,
        family_members: ['Randolph Spudmore (son)', 'Spudmore family'],
        gender: 'Male',
        hair_color: null,
        height: null,
        house: null,
        image: null,
        jobs: ['Broom-maker'],
        marital_status: null,
        name: 'Able Spudmore',
        nationality: null,
        patronus: null,
        romances: [],
        skin_color: null,
        species: 'Human',
        titles: [],
        wands: [],
        weight: null,
        wiki: 'https://harrypotter.fandom.com/wiki/Able_Spudmore',
      },
    },
  ],
  meta: {
    pagination: {
      current: 2,
      first: 1,
      prev: 1,
      next: 3,
      last: 3,
      records: 20,
    },
  },
  links: {
    first: 'link',
    last: 'link',
    next: 'link',
    prev: 'link',
  },
};

export const responseDataForChar: ApiResponseForCharType = {
  data: {
    id: '20448207-20d2-48cb-85b4-d61ee8f50f97',

    attributes: {
      slug: '1992-gryffindor-vs-slytherin-quidditch-match-spectators',
      alias_names: [],
      animagus: null,
      blood_status: null,
      boggart: null,
      born: null,
      died: null,
      eye_color: null,
      family_members: [],
      gender: null,
      hair_color: null,
      height: null,
      house: null,
      image: null,
      jobs: [],
      marital_status: null,
      name: '1992 Gryffindor vs Slytherin Quidditch match spectators',
      nationality: null,
      patronus: null,
      romances: [],
      skin_color: null,
      species: null,
      titles: [],
      wands: [],
      weight: null,
      wiki: 'https://harrypotter.fandom.com/wiki/1992_Gryffindor_vs_Slytherin_Quidditch_match_spectators',
    },
  },

  meta: {
    copyright: '',
    generated_at: '',
  },
  links: {
    self: '',
  },
};

export const responseDataForCharSecond: ApiResponseForCharType = {
  data: {
    id: '20448207-20d2-48cb-85b4-d61ee8f50f97',

    attributes: {
      slug: '1992-gryffindor-vs-slytherin-quidditch-match-spectators',
      alias_names: [],
      animagus: null,
      blood_status: null,
      boggart: null,
      born: null,
      died: null,
      eye_color: null,
      family_members: [],
      gender: null,
      hair_color: null,
      height: null,
      house: null,
      image: null,
      jobs: [],
      marital_status: null,
      name: '1992 Gryffindor vs Slytherin Quidditch match spectators',
      nationality: null,
      patronus: null,
      romances: [],
      skin_color: null,
      species: null,
      titles: [],
      wands: [],
      weight: null,
      wiki: 'https://harrypotter.fandom.com/wiki/1992_Gryffindor_vs_Slytherin_Quidditch_match_spectators',
    },
  },

  meta: {
    copyright: '',
    generated_at: '',
  },
  links: {
    self: '',
  },
};

export const paginationMockState = {
  current: 1,
  first: 1,
  prev: 1,
  next: 2,
  last: 5,
  records: 100,
};
